import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@repo/ui/components/ui/accordion";

interface FAQProps {
  question: string;
  answer: string;
  value: string;
}

const FAQListEn: FAQProps[] = [
  {
    question: "How does your app work?",
    answer: "Our app connects to Stability APIs, which use artificial intelligence models to generate realistic and unique images. You provide parameters such as the subject of the image, desired style and other details, then our application uses this information to create a personalized image.",
    value: "item-2",
  },
  {
    question: "Can I use the generated images for commercial purposes?",
    answer: "Yes, you can use the images generated by our application for personal and commercial purposes, subject to the specified terms of use. Please see our Terms of Use for more details.",
    value: "item-3",
  },
  {
    question: "What is the quality of the images generated by your application?",
    answer: "The images generated by our application are of high quality and can rival those created by professional artists. We use advanced models and state-of-the-art algorithms to ensure impressive results.",
    value: "item-4",
  },
  {
    question: "Are there any limitations on the number of images I can generate?",
    answer: "We offer different subscription options which may include limitations on the number of images you can generate. Please see our subscription plans for details on limitations and available features. We offer dedicated customer support to answer all your questions and resolve any issues you may encounter. You can contact us via our contact form or by email at contact@midas.com.",
    value: "item-5",
  },
];

const FAQListFr: FAQProps[] = [
  {
    question: "Comment fonctionne votre application ?",
    answer: "Notre application se connecte aux API de stabilité, qui utilisent des modèles d'intelligence artificielle pour générer des images réalistes et uniques. Vous fournissez des paramètres tels que le sujet de l'image, le style souhaité et d'autres détails, puis notre application utilise ces informations pour créer une image personnalisée.",
    value: "item-2",
  },
  {
    question: "Puis-je utiliser les images générées à des fins commerciales ?",
    answer: "Oui, vous pouvez utiliser les images générées par notre application à des fins personnelles et commerciales, sous réserve des conditions d'utilisation spécifiées. Veuillez consulter nos conditions d'utilisation pour plus de détails.",
    value: "item-3",
  },
  {
    question: "Quelle est la qualité des images générées par votre application ?",
    answer: "Les images générées par notre application sont de haute qualité et peuvent rivaliser avec celles créées par des artistes professionnels. Nous utilisons des modèles avancés et des algorithmes de pointe pour garantir des résultats impressionnants.",
    value: "item-4",
  },
  {
    question: "Y a-t-il des limites au nombre d'images que je peux générer ?",
    answer: "Nous proposons différentes options d'abonnement qui peuvent inclure des limitations sur le nombre d'images que vous pouvez générer. Veuillez consulter nos plans d'abonnement pour plus de détails sur les limitations et les fonctionnalités disponibles. Nous proposons un support client dédié pour répondre à toutes vos questions et résoudre tous les problèmes que vous pourriez rencontrer. Vous pouvez nous contacter via notre formulaire de contact ou par email à contact@midas.com.",
    value: "item-5",
  },
];

export const FAQ = () => {
  return (
    <section
      id="faq"
      className="container py-24 sm:py-32"
    >
      <h2 className="text-3xl md:text-4xl font-bold mb-4">
        Frequency {" "}
        <span className="bg-linear-to-b from-primary/60 to-primary text-transparent bg-clip-text">
          Question
        </span>
      </h2>
        <Accordion
          type="single"
          collapsible
          className="w-full AccordionRoot"
        >
          {FAQListEn.map(({ question, answer, value }: FAQProps) => (
            <AccordionItem
              key={value}
              value={value}
            >
              <AccordionTrigger className="text-left font-semibold">
                {question}
              </AccordionTrigger>

              <AccordionContent className="text-[1vw]">{answer}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>


      <h3 className="font-medium mt-4">
       Still {" "}
        <a
          href={`/contact`}
          className="text-primary transition-all border-primary hover:border-b-2"
        >
          Contact
        </a>
      </h3>
    </section>
  );
};