export enum FineTuneStatus {
  PENDING = "PENDING",
  PREPARING = "PREPARING",
  TRAINING = "TRAINING",
  VALIDATING = "VALIDATING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}
