export enum WeaponCategory {
  HANDGUN = "HANDGUN",
  RIFLE = "RIFLE",
  SHOTGUN = "SHOTGUN",
  SUBMACHINE_GUN = "SUBMACHINE_GUN",
  ASSAULT_RIFLE = "ASSAULT_RIFLE",
  SNIPER_RIFLE = "SNIPER_RIFLE",
  MACHINE_GUN = "MACHINE_GUN",
  GRENADE_LAUNCHER = "GRENADE_LAUNCHER",
  MISSILE = "MISSILE",
  EXPLOSIVE = "EXPLOSIVE",
  MELEE = "MELEE",
  OTHER = "OTHER",
}
